version: '2'

services:

    dachs:
        container_name: myDachs
        build: ./images/dachs
        image: dachs:chbrandt
        tty: true
        network_mode: 'bridge'
        ports:
            - '80:80'
        volumes:
            - dachs_data:/var/gavo
        links:
            - postgres
        depends_on:
            - postgres

    postgres:
        container_name: myPostgres
        build: ./images/postgres
        image: postgres:chbrandt
        tty: true
        network_mode: 'bridge'
        volumes:
            - postgres_data:/var/lib/postgresql/9.4/main

volumes:
  postgres_data:
  dachs_data:
